import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Music Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/" />
      </Head>

      <main>
        <div className="text-6xl text-red-500">hi there</div>
      </main>

      <footer></footer>
    </>
  )
}

export default Home
